[익조] 스프링 카페 4단계 - 로그인 구현
codesquad-members-2022/java-spring-cafe pull request #112
Opened 2022-03-16 09:58 UTC by ikjo93

안녕하세요!! 익조입니다!! 😁

"스프링 카페 3단계 - DB에 저장하기" 구현 부분과 관련하여, 작성한 소스 코드 파일을 첨부드리오니 확인부탁드립니다. :)

배포 URL : https://ikjo-spring-cafe.herokuapp.com/

아울러 미션 구현 세부 내용, 웹 앱의 이벤트 흐름도 등 미션 관련 사항은 별도 README 파일에 작성하였습니다.

### 고민했었던 부분
1. 컨트롤러의 역할과 책임 관점에서 사용자 로그인 및 로그아웃에 대한 컨트롤러 역할을 기존 UserController에서 해야할지 어떤 로그인/로그아웃과 관련된 별도 컨트롤러를 생성해야할 지 고민이 되었습니다. 개인적으로는 사용자 로그인과 로그아웃은 사용자 정보에 대한 내용을 검증/처리하는 내용과 관련있다고 생각해서 기존 UserController를 활용했습니다.

2. 로그아웃 처리 시 매개변수로 받은 HttpSession에 대해 removeAttribute를 활용하여 당초 로그인 시 설정했던 sessionUser에 대한 설정 값만 제거할지, invalidate를 활용하여 세션의 모든 속성을 다 제거할지 고민이 되었습니다. 개인적인 생각으로 모든 사용자에 대해 초기화(invalidate)를 시켜주지 않으면 서버 입장에서는 사용자들의 세션 정보를 계속 가지고 있게되므로 부담이 되고 아울러 잠재적으로 보안상의 문제도 있을 수 있기 때문에 removeAttribute보다는 invalidate를 사용했습니다.

<br/>

감사합니다!!

2022-03-16 09:59 UTC, ikjo93 commented
앗 Pull Request 본문에 --> "스프링 카페 3단계 - DB에 저장하기" 구현 부분과 관련하여 <-- 이 부분 오타입니다 ㅠㅠ 4단계입니다!!

2022-03-19 11:46 UTC, wheejuni requested changes
수고 많으셨습니다. 💯 
간단한 수정 두 가지만 하고 다음 단계로 넘어가보면 좋을 것 같네요.

2022-03-19 11:46 UTC, wheejuni commented on src/main/java/com/kakao/cafe/controller/ExceptionController.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
조금 더 구체적인 상태코드를 생각해 보시면 어떨까요?

2022-03-19 11:46 UTC, wheejuni commented on src/main/java/com/kakao/cafe/service/UserService.java
> +    public void validateSessionOfUser(String id, HttpSession session) {
표현 계층에만 갇혀있어야 할 `HttpSession` 클래스를 여기에서 받아 쓰는 것은 그렇게 좋은 설계는 아닌 것 같습니다~
컨트롤러에서 필요한 정보를 빼내어 여기에 보내주는 형태로 변경을 해야할 것 같네요.

2022-03-19 12:21 UTC, ikjo93 commented on src/main/java/com/kakao/cafe/service/UserService.java
> +    public void validateSessionOfUser(String id, HttpSession session) {
감사합니다!! 말씀하신 내용대로 HttpSession에 있는 필요한 정보를 빼내어 서비스단에서 처리하도록 수정했습니다!!

2022-03-19 12:23 UTC, ikjo93 commented on src/main/java/com/kakao/cafe/controller/ExceptionController.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
넵!! BAD_REQUEST는 너무 추상적인 상태코드 같아, 로그인 실패 시에는 Unauthorized로, 사용자가 권한이 없는 접근을 할 경우에는 Forbidden로 수정하였습니다!!

2022-03-19 12:24 UTC, ikjo93 commented
@wheejuni
안녕하세요!! Brian!! 주말에도 코드 리뷰해주셔서 감사드립니다!! 말씀해주신 리뷰 사항도 반영하였으니 확인 부탁드립니다~! 😁

2022-03-19 12:25 UTC, merged