[zzangmin] 4단계
codesquad-members-2022/java-spring-cafe pull request #124
Opened 2022-03-17 10:51 UTC by leezzangmin

### 안녕하세요. 리뷰해주셔서 감사합니다.

영한님 mvc2 강의를 보고 적용해보았습니다.

2022-03-20 06:30 UTC, wheejuni requested changes
변경사항이 많지는 않군요. 
간단한 포인트 하나만 짚어보고 넘어가면 될 것 같습니다.

2022-03-20 06:30 UTC, wheejuni commented on build.gradle
> +	implementation group: 'na.net.ultraq.thymeleaf', name: 'thymeleaf-layout-dialect', version:'2.5.2'
헉 제가 평소에 보고 쓰던 타임리프 라이브러리랑 네임스페이스가 좀 다르네요?

어떤 거죠?

2022-03-20 06:30 UTC, wheejuni commented on src/main/java/com/kakao/cafe/service/UserService.java
> +        return user.matchPassword(password);
여기 NullPointerException 발생할 우려는 아예 없는 걸까요?

2022-03-21 12:10 UTC, leezzangmin commented on build.gradle
> +	implementation group: 'na.net.ultraq.thymeleaf', name: 'thymeleaf-layout-dialect', version:'2.5.2'
레이아웃 병합하면서 블로그에서 본 글 따라하다가 그대로 남았네요. 수정하겠습니다

2022-03-21 12:15 UTC, leezzangmin commented on src/main/java/com/kakao/cafe/service/UserService.java
> +        return user.matchPassword(password);
생각해보니 그렇군요!!
Optional을 코드에 전체적으로 적용하는게 Best라고 하는데, 아직 수련이 부족해 생각하지 못했습니다. 우선 해당 메서드에 if문으로 조건을 체크하는 식으로 구현하고, 후에 Optional을 학습해서 전체적으로 적용하는 방향으로 가겠습니다..!!

2022-04-01 13:01 UTC, merged