[후] 스프링 카페 3단계 - DB에 저장하기
codesquad-members-2022/java-spring-cafe pull request #129
Opened 2022-03-18 02:07 UTC by who-hoo

안녕하세요! 스프링 카페 3단계 PR 요청 드립니다. 항상 감사합니다 :)

## 변경 사항
- [x]  H2 데이터베이스 연동
- [x] Heroku를 이용한 배포
    - 배포 URL : https://spring-cafe-hoo.herokuapp.com/

2022-03-20 12:27 UTC, wheejuni requested changes
대단히 수고 많으셨습니다. 💯 
몇가지 생각해보시면 좋을 점 코멘트로 남겨드립니다~

2022-03-20 12:27 UTC, wheejuni commented on src/main/java/com/kakao/cafe/domain/Article.java
> +    private final Integer id;
`id` 를 `Integer` 로 저장하는 것.. 괜찮을까요?
괜찮다고 쉽게 생각할 수는 있지만 권장하지는 않습니다. _왜 권장하지 않을까요?_

2022-03-20 12:27 UTC, wheejuni commented on src/main/java/com/kakao/cafe/domain/Article.java
> +        AtomicInteger viewCount, LocalDateTime createdAt) {
`viewCount` 가 `AtomicInteger` 인 이유도 궁금해요.

2022-03-20 12:27 UTC, wheejuni commented on src/main/java/com/kakao/cafe/domain/User.java
> +    public User(int id, User user) {
`Integer` 와 `int` 사이에 변환이 일어날 때 생각해볼 만한 리스크는 없을까요?

2022-03-20 12:27 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/H2ArticleRepository.java
> +public class H2ArticleRepository implements ArticleRepository {
클래스명에 특정 기술/라이브러리/프레임워크가 들어가는 것에 강하게 반대합니다.
이렇게 특정 기술에 종속되지 않으려고 클래스를 나누고, 인터페이스를 분리하는 것이라고 생각합니다. 
그리고 `H2` 와 `MySQL` 이 레포지토리가 달라야 하는 이유도 잘 모르겠습니다.
그 둘은 완벽하게 호환되어서 서로의 존재를 몰라도 로컬 테스트/디버깅이 용이하게끔 사용하는 목적이 있습니다.
왜 달라야 하죠?

2022-03-20 12:27 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/H2ArticleRepository.java
> +        return update(article);
있거나 없거나 하나의 쿼리로 처리하는 방식은 없으려나요?

2025-09-25 02:27 UTC, closed without merging

2025-09-30 02:52 UTC, honux77 commented
@who-hoo 갑자기 커밋 정리중이군요 ㅋㅋㅋ