[산토리] 스프링 카페 5단계 - 게시글 권한부여
codesquad-members-2022/java-spring-cafe pull request #132
Opened 2022-03-18 06:35 UTC by seyoung755

안녕하세요 리뷰어님!! 산토리입니다.
스프링 카페 미션 5단계를 구현하여 PR드립니다.
지난 리뷰 때 여쭤봤던 예외 처리 관련한 답변 감사합니다. 관련해서 많은 생각을 할 수 있었습니다.
단순히 검증하는 역할과 검증 결과를 토대로 판단하는 역할을 분리해야 된다는 걸 느꼈던 것 같습니다.

## 주요 사항 

## Step 05: 게시글 권한부여

### TO-DO

- [x] 5단계 요구사항 적용해보기
  - [x] 비로그인 사용자는 글 목록만 볼 수 있다.
  - [x] 로그인한 사용자는 글을 작성/조회/삭제할 수 있다. (삭제 기능을 추가해야 한다.)
- [x] 게시글 작성 관련 기능 구현
  - [x] 게시글 작성 시 글쓴이 입력 필드를 삭제하고 세션에 저장된 유저 이름(name)을 입력한다.
    - [x] 글 목록에서 사용자 아이디를 누르면 프로필로 이동하는 기능 구현해보기
  - [x] 비로그인 사용자가 권한이 없는 페이지로 접속하면 로그인 페이지로 이동한다.
- [x] 게시글 수정 관련 기능 구현
  - [x] 게시글 수정 화면과 수정 요청은 로그인 사용자와 글쓴이 아이디가 같은 경우에만 가능하다.
  - [x] 다른 경우엔 에러 페이지를 출력한다.
- [x] 게시글 삭제 관련 기능 구현
  - [x] 삭제의 경우에도 게시글 수정과 같이 구현한다.
- [ ] 예외 처리 시 http stauts code 관리해보기 (현재는 500이 나온다)

### 고민
- Controller단에서는 검증이 가능한데 query로 직접 insert 가능한 예외에 대해서는 어떻게 처리해야 할까요?
ex) insert query로 존재하지 않는 사용자의 이름을 작성자로 하여 저장하는 경우

2022-03-21 00:30 UTC, tmdgusya requested changes
고생하셨습니다. 몇가지만 수정하시고 다음 단계로 넘어가시죠 ㅎㅎ 👍

2022-03-21 00:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/controller/ArticleController.java
> +        if (sessionUser == null || !((User) sessionUser).getUserId().equals(writer)) {
`((User) sessionUser).getUserId().equals(writer))` 이런 경우는 User 안에 isSameWriter 같은걸 만드시는걸 추천해요.
이렇게 유저의 속성을 가져와서 외부에서 비교하게 되면 나중에 고쳐야할 지점이 많아져요. 디미터의 법칙에 대해서 공부해보세요.

2022-03-21 00:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/controller/ArticleController.java
> +        if (!user.getUserId().equals(requestDto.getWriter())) {
간단하게 예를 들면 만약에 userId 에 대한 스펙을 바꾸면 위아래 코드 모두 수정해야 할거에요
왜냐면 책임 분리가 명확히 안되어 있기 때문이죠.

2022-03-21 00:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/WebConfig.java
> +                .excludePathPatterns("/", "/css/**", "/images/**", "/error", "/users", "/users/login", "/users/join", "/users/create");
👍

2022-03-21 00:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/controller/interceptor/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
요렇게 했을때 나중에 점점 excludePattern 에 코드가 추가가 너무 많이 되서
권한이 필요한 부분만 따로 prefix url 을 쓰게 될수도 있어서 특정표식(annotation) 이 들어간애들만 권한 검증을 하게 하는것도 좋은 방법이에요. 예를 들면 Controller 메소드 중에 `@Auth` 이런게 붙어있는 애들만 검증한다. 이런 방식처럼 말이죠.

2022-03-21 00:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/controller/interceptor/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
약간 어려울 수 있으니 나중에 바꿔보시는걸 추천드려요

2022-03-21 00:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/Article.java
> +    }
👍

2022-03-21 00:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/controller/interceptor/LoginInterceptor.java
> +        return true;
그래도 Interceptor 까지 공부해서 적용하셨군요 👍

2022-03-21 00:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/ArticleJdbcTemplateRepository.java
> +        String query = "delete from article where id = " + id;
이런식으로 Query 를 작성하게 되면 `SQL Injection` 이라는 공격에 취약할 수 있어요.
이 부분은 대부분의 기업 면접에서 물어보는 문제 중 하나에요.
JDBC 를 사용해봤다면 물어보는 키워드 중 하나이므로 이 부분을 어떻게 해결해야 할지 공부해보시고, 주변 동료분들에게도 공유해주세요 💯

2022-03-21 00:30 UTC, tmdgusya commented on src/main/resources/sql/ddl.sql
> +INSERT INTO USER (user_id, password, name, email) VALUES ('santori', '1234', '짭토리', 'santori@naver.com');
이런 아이들은 ddl 은 아니여서 init.sql 으로 네이밍을 바꾸시는건 어떠실까해요

2022-03-21 00:30 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/controller/interceptor/LoginInterceptorTest.java
> +    @DisplayName("세션이 없으면 로그인 페이지로 리다이렉트된다")
👍

2022-03-23 10:27 UTC, merged

2022-03-27 13:10 UTC, seyoung755 commented on src/main/java/com/kakao/cafe/controller/ArticleController.java
> +        if (sessionUser == null || !((User) sessionUser).getUserId().equals(writer)) {
리뷰 반영이 늦어 죄송합니다 ㅠㅠ 이 부분은 별 생각없이 그냥 검사만 하는 데에 급급했던 것 같은데 말씀해주신 내용을 보니 문제가 있는 코드네요! 디미터의 법칙도 저번에 말씀해주셨는데 무의식적으로 많은 곳에서 어기고 있는 것 같습니다! User 객체 내에서 비교하도록 메서드를 만들어 보겠습니다 👍

2022-03-27 13:26 UTC, seyoung755 commented on src/main/java/com/kakao/cafe/controller/ArticleController.java
> +        if (!user.getUserId().equals(requestDto.getWriter())) {
위 아래 코드 중복되는 부분이 있다는 걸 놓쳤었네요..! 리팩토링해보겠습니다!

2022-03-27 13:26 UTC, seyoung755 commented on src/main/java/com/kakao/cafe/controller/interceptor/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
아 그렇군요! 규모가 커질 경우에 권한 관련 처리를 할 때 참고하겠습니다 !!

2022-03-27 13:27 UTC, seyoung755 commented on src/main/java/com/kakao/cafe/domain/article/ArticleJdbcTemplateRepository.java
> +        String query = "delete from article where id = " + id;
넵 해당 부분 학습해보겠습니다~!