[Miller] 스프링 카페 6단계 - 댓글
codesquad-members-2022/java-spring-cafe pull request #136
Opened 2022-03-19 09:05 UTC by rxdcxdrnine

안녕하세요, 6단계 PR 을 올린 Miller 입니다 😀😀

## 기능 요구 사항

### 6단계

- 사용자의 댓글 추가, 수정, 삭제 및 조회 (CRUD) 구현

<추가 요구사항>
- 댓글이나 게시글 삭제 시 데이터의 삭제가 아닌, 삭제 상태 (delete - boolean type) 로 변경
- 댓글이 없는 경우, 게시글 작성자와 댓글 작성자가 같은 경우 게시글 삭제 가능
- 게시글 작성자와 댓글이 작성자가 같은 경우 삭제 가능

## 배포 링크

heroku 배포 링크 : <https://java-spring-cafe.herokuapp.com>

테스트 ID/비밀번호 : javajigi / test

2022-03-22 09:47 UTC, tmdgusya requested changes
6단계 미션 고생하시느라 고생 많으셨습니다.
학습한 흔적들이 많이 보이네요 👍 

몇가지만 고치고 다음 단계로 넘어가시죠

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/controller/ArticleController.java
> +    // article
questions 는 뭐고 articles 는 뭔가요?

둘다 근데 코드는 같아서.. 통일을 하셔야될거 같은데요?

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/Article.java
>      }
저는 이렇게 생성자가 많다면 목적에 따른 의미를 부여하기 위해 `Factory Method Pattern` 을 사용하시는 것을 추천드려요.
한번 학습해보시고 사용해보세요.

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/dto/ReplyResponse.java
> +    }
👍

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/dto/ArticleResponse.java
> +    }
여기도 다르게 들어가는 이유가 있을거 같은데 FactoryMethodPattern 으로 어떤 의도 인지 함수로 표현해주세요~!

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/exception/ErrorCode.java
> +    INVALID_ARTICLE_DELETE(HttpStatus.FORBIDDEN, "다른 유저의 댓글이 등록된 질문은 삭제할 수 없습니다.");
HTTP 상태값 좋네요.

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/repository/jdbc/ArticleJdbcRepository.java
> +                count ? rs.getInt(REPLY_COUNT) : null
`flag` 변수를 통해서 컨트롤 하시는 군요.

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/repository/jdbc/ArticleJdbcRepository.java
> +                count ? rs.getInt(REPLY_COUNT) : null
아마 변수명을 지을 때 많은 고민을 하셨겠지만 변수명이 `count` 이고 변수의 Type 이 Boolean 인 경우에 어떤 의미인지 알기 힘들거 같아요. 좀 더 좋은 이름으로 바꿔주세요.

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/service/ArticleService.java
> +        return ArticleResponse.from(article);
👍

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/service/ArticleService.java
> +        }
`isDeletable` 표현 좋네요 👍

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/service/ReplyService.java
> +        user.checkUserId(reply.getUserId());
깔끔하네요.
주석은 딱히 없어도 될거같지만 일부러 달아놓으신거라 생각하고 피드백 안드리겠습니다.

2022-03-22 09:47 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/integration/controller/ArticleControllerTest.java
> +            .andExpect(view().name("redirect:/"));
메인페이지로 이동한다. 보다 Redirect 이므로 `댓글을 삭제하면 메인페이지로 이동된다` 라는 표현이 좀 더 좋지 않을까 싶어요.

2022-03-22 09:47 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/session/SessionUser.java
> +    public void checkUserId(String userId) {
👍 
이건 컨벤션 찾아보고 하신건가요 ㅎㅎ? 좋네요

2022-03-22 09:47 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/integration/controller/ArticleControllerTest.java
혹시 이 클래스는 왜 존재하는건가요?

2022-03-22 09:47 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/integration/repository/ReplyJdbcRepositoryTest.java
> +public class ReplyJdbcRepositoryTest {
실제 DB 에 테스트 하는 방법을 택하셨군요 ㅎㅎ 👍 
이렇게 하신 이유가 있으실거 같은데 하신 이유를 들려주실수 있나요? 단순히 궁금해서 질문했습니다 ㅎㅎ

2022-03-23 10:28 UTC, merged

2022-03-26 08:15 UTC, rxdcxdrnine commented on src/main/java/com/kakao/cafe/controller/ArticleController.java
> +    // article
요구사항에 주어진대로 질문을 등록할 때는 `questions` path 아래의 API 에 접근하고, 이미 등록된 질문에 접근할 때는 `articles` path 아래의 API 에 접근하도록 구성했습니다. 그리고 DB 에 저장할 때도 마찬가지로 요구사항에 주어진대로 `Article` 객체를 저장하도록 했는데, 제가 보기에도 헷갈리는 부분입니다. 현재 전반적으로 클래스 이름이나 변수 이름이 `article` 과 관련해 구성되어 있으므로, `article` 쪽으로 통일하도록 하겠습니다!

2022-03-26 08:56 UTC, rxdcxdrnine commented on src/main/java/com/kakao/cafe/domain/Article.java
>      }
넵! 객체의 모든 속성을 인자로 입력받는 생성자 외의 다른 생성자의 경우에는, `createWithInputOnly`, `createWithOutReplyCount` 와 같이 별도의 팩토리 메서드를 만들겠습니다.

2022-03-26 09:09 UTC, rxdcxdrnine commented on src/main/java/com/kakao/cafe/dto/ArticleResponse.java
> +    }
넵! 점층적 생성자 여러 개 대신, `createArticleResponse` 와 같은 팩토리 메서드로 대체하겠습니다.

2022-03-26 09:11 UTC, rxdcxdrnine commented on src/main/java/com/kakao/cafe/repository/jdbc/ArticleJdbcRepository.java
> +                count ? rs.getInt(REPLY_COUNT) : null
넵! 메서드의 인자 이름을 `isReplyCountContained` 로 변경하겠습니다.

2022-03-26 09:13 UTC, rxdcxdrnine commented on src/main/java/com/kakao/cafe/service/ReplyService.java
> +        user.checkUserId(reply.getUserId());
감사합니다! 서비스 계층의 비즈니스 로직의 경우, 리뷰어께서 이해하사는데 어려움이 없도록 각 라인마다 주석을 추가했습니다.

2022-03-26 09:14 UTC, rxdcxdrnine commented on src/main/java/com/kakao/cafe/session/SessionUser.java
> +    public void checkUserId(String userId) {
앗 컨벤션을 보고한 것은 아니지만 .. 감사합니다!

2022-03-26 09:17 UTC, rxdcxdrnine commented on src/test/java/com/kakao/cafe/integration/controller/ArticleControllerTest.java
> +            .andExpect(view().name("redirect:/"));
이전에 리뷰해 주신대로, 메서드의 실행 결과는 실행 주체에 호출에 의한 결과 값이므로 `...이동된다` 와 같이 수동적인 표현을 사용하려고 했는데, 놓친 부분이 있는 것 같습니다. 감사합니다!

2022-03-26 09:28 UTC, rxdcxdrnine commented on src/test/java/com/kakao/cafe/integration/controller/ArticleControllerTest.java
`UserController` 클래스의 통합 테스트를 위해 만든 테스트 클래스입니다. 컨트롤러 계층의 경우, 내부에서 호출하는 서비스 계층을 목 객체로 만들고 오로지 컨트롤러 계층의 코드만을 테스트하기 위한 별도의 단위 테스트가 `com.kakao.cafe.unit.controller` 패키지에 존재합니다.

해당 통합 테스트에서는 목 객체를 만들지 않고, 애플리케이션 컨텍스트에 등록된 모든 빈을 스프링 컨테이너에 생성하고, 데이터베이스를 연결해 테스트를 진행했습니다. 컨트롤러 계층의 테스트인만큼, `MockMvc` 객체를 이용해 컨트롤러에 등록된 API 를 호출하도록 요청을 보내는 테스트를 작성했습니다.

2022-03-26 09:36 UTC, rxdcxdrnine commented on src/test/java/com/kakao/cafe/integration/repository/ReplyJdbcRepositoryTest.java
> +public class ReplyJdbcRepositoryTest {
실제 데이터베이스에 저장된 데이터를 직접 눈으로 확인하기 위해, 위와 같이 어노테이션을 사용했습니다!

`@AutoConfigureTestDatabase(replace = Replace.ANY)` 로 테스트 시에 Embedded H2 데이터베이스를 사용하면, H2 데이터베이스 외에 MySQL 등 다른 데이터베이스를 연결했을 때 테스트 실행 후 저장되거나 삭제된 데이터를 확인할 수 없었습니다.

데이터가 저장됐는지 확인할 땐 `@Rollback(false)` 어노테이션을 사용했는데, 해당 어노테이션은 잠깐씩 데이터를 확인할 때만 사용하고, 일괄적인 테스트를 방해하지 않기 위해 바로 지워 커밋 기록에 포함되지 않았습니다.