[로니] 스프링 카페 5단계 - 게시글 권한부여
codesquad-members-2022/java-spring-cafe pull request #137
Opened 2022-03-19 11:54 UTC by CMSSKKK

안녕하세요! 로니입니다.

5단계 PR을 보냅니다. 

게시글을 수정하는 로직을 짜면서 많은 수정과 고민을 하였습니다.
아직도 빈틈이 많은 것 같고 가독성도 나쁜 것 같아 스스로도 만족스럽지 않습니다. 
하지만 6단계에서 댓글 기능을 추가하게 되었을 때 더 고민하고 수정할 수 있으리라 생각하고 PR을 보냅니다!

감사합니다!

2022-03-22 10:22 UTC, tmdgusya requested changes
고생하셨습니다. 
여러가지로 학습하신 부분들이 보이네요 ㅎㅎ 👍 
코드가 점점 깔끔해지는 거 같은 느낌이 들어요

몇가지만 고치고 넘어가시죠.

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/constants/LoginConstants.java
> +}
constant 파일을 따로 만드셨군요.
근데 자바에서는 오히려 엄청 좋은 방법인지는 모르겠어요 저는 오히려 클래스에 있는게 좋지 않나 라는 생각이 들어요.
근데 이건 생각차이 일수도 있으니 일단 넘어가도록 할께요 :)

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/Article.java
> +    public Article(Integer id, String writer, String title, String contents, LocalDateTime writtenTime) {
저는 생성자가 보통 여러개가 생기면 `FactoryMethodPattern` 을 이용해서 함수의 이름을 이용해 의미에 맞는 생성자를 제공하는 편이에요.

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/Article.java
> +        return Objects.equals(getId(), article.getId());
Integer class 안에 equals 라는 메소드가 존재하지 않나요?
Objects.equals 를 쓸 이유가 있나 싶어 물어봅니다.

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/Article.java
> +        return Objects.equals(getId(), article.getId());
이 참에 `Object.eqauls` 메소드도 한번 살펴보시는걸 추천드려요.

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/JdbcTemplateArticleRepository.java
> +        return update(article);
심플하네요 👍

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/JdbcTemplateArticleRepository.java
> +        int result = jdbcTemplate.update(sql, new MapSqlParameterSource("id", id));
으로 단축가능해보이지 않나요 ㅎㅎ?


```java
return jdbcTemplate.update(sql, new MapSqlParameterSource("id", id)) == 1 
```

좀더 가독성을 높이고 싶으면 1 을 상수로 빼서 DELETE_COMPLETE 이런식으로 해도 좋을거 같네요.

```java
final int DELETE_COMPLETE = 1
return jdbcTemplate.update(sql, new MapSqlParameterSource("id", id)) == DELETE_COMPLETE
```

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/interceptor/LoginInterceptor.java
> +public class LoginInterceptor implements HandlerInterceptor {
Interceptor 를 사용하셨군요 ㅎㅎ

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/service/ArticleService.java
> +        return deleted;
그냥 바로 return 해도 좋을거 같아요 ㅎㅎ

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/service/ArticleService.java
> +            throw new ClientException(HttpStatus.FORBIDDEN, "접근 권한이 없습니다.");
상태코드 좋네요

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +        logger.info("[{}] writing qna{}", sessionedUserUserId, articleDto);
오 로그도 보기 좋은 로그 같아요. 
로그도 신경쓰는 습관을 들이면 아주 좋답니다 ㅎㅎ

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +        UserResponseDto sessionedUser = (UserResponseDto) httpSession.getAttribute(LoginConstants.SESSIONED_USER);
세션에 맞는 모델을 하나 만들어주는게 좋지 않을까 싶어요 ㅎㅎ
뭔가 추론이 안되요. 만약 단순히 속성이 같다고 이용했다면 그건 별로 좋지 않은 습관입니다.
책임이 중복될 수 있어요

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +            throw new ClientException(HttpStatus.FORBIDDEN, "접근 권한이 없습니다.");
Error 가 나는 부분에서는 Logger.info 보다는 logger.error 로 찍어주세요~!

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/UserController.java
> +        logger.info("[{}] failed login", loginDto.getUserId());
여기도 마찬가지로 실패한 경우는 Info 보다 warn / error 로 찍어주세요 ㅎㅎ

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/dto/ArticleDto.java
>      }
차라리 ArticleDto 에 변환하는 Entity 가 두개일경우에는 모델도 두개여야 할꺼같아요.
UpdateArticleDto 이런식으로

2022-03-22 10:22 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/dto/ArticleDto.java
>      }
사용처에 맞게 하나씩 사용해주시는걸 추천드려요

2022-03-22 10:22 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/domain/article/JdbcTemplateArticleRepositoryTest.java
> +    @DisplayName("delte 시 해당 게시글을 삭제한다.")
ㅎㅎ `delete` 깜빡하신거 같네요

2022-03-22 10:22 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/web/ArticleControllerTest.java
> +    @DisplayName("/qna/update/{id} put 요청시 게시글을 수정 후 /qna/show/{id}로 리다이렉션한다.")
되게 꼼꼼히 적으시네요 ㅎㅎ 좋은거 같아요

2022-03-23 10:28 UTC, merged

2022-03-24 12:16 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/domain/article/Article.java
> +    public Article(Integer id, String writer, String title, String contents, LocalDateTime writtenTime) {
저도 많이 고민했던 부분입니다 ㅠㅠ 짚어주셔서 감사합니다!

2022-03-24 12:18 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/domain/article/JdbcTemplateArticleRepository.java
> +        int result = jdbcTemplate.update(sql, new MapSqlParameterSource("id", id));
훨씬 간결해지는군요🤭  예시까지 너무 감사합니다!

2022-03-24 12:20 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +        logger.info("[{}] writing qna{}", sessionedUserUserId, articleDto);
로치가 이전 단계에 코멘트 주셔서 신경쓰고 있습니다! 감사합니다ㅎㅎ

2022-03-24 12:21 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +        UserResponseDto sessionedUser = (UserResponseDto) httpSession.getAttribute(LoginConstants.SESSIONED_USER);
저도 많이 고민했던 부분인데, 같은 속성이라 중복이라고 생각했던 것 같고 추후에 Dto 클래스 이름을 변경해야하나 생각했습니다. 
책임이 다르다고 생각하니깐 하나 만드는 편이 훨씬 좋은 것 같습니다 . 수정하겠습니다 ! ㅎㅎ

2022-03-24 12:22 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +            throw new ClientException(HttpStatus.FORBIDDEN, "접근 권한이 없습니다.");
넵! 변경하겠습니다.

2022-03-24 12:23 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/web/dto/ArticleDto.java
>      }
이것도 구현하면서 많이 찝찝했던 부분입니다! Dto를 의미없이 너무 많이드는 것 아닌가 했었는데, 짚어주셔서 정말 감사합니다 ㅎㅎ

2022-03-24 12:23 UTC, CMSSKKK commented on src/test/java/com/kakao/cafe/domain/article/JdbcTemplateArticleRepositoryTest.java
> +    @DisplayName("delte 시 해당 게시글을 삭제한다.")
넵 ㅎㅎ 수정하겠습니다 😂

2022-03-24 12:24 UTC, CMSSKKK commented on src/test/java/com/kakao/cafe/web/ArticleControllerTest.java
> +    @DisplayName("/qna/update/{id} put 요청시 게시글을 수정 후 /qna/show/{id}로 리다이렉션한다.")
로치 코멘트 덕분에 좋은 코딩 습관 가지도록 노력하게 되는 것 같습니다.

항상 감사합니다 로치!

2022-03-24 12:43 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/domain/article/Article.java
> +        return Objects.equals(getId(), article.getId());
`equals`의 경우 intellij를 통해서 자동처럼 오버라이딩했었는데, 쓰임을 잘 모르고 사용한 것 같습니다.

`Object.equals` 또한 오버라이딩 하지 않으면 단순히 `==`의 역할을 하는 메서드이군요.

키워드 정말 감사합니다🙇‍♂️