[Yan] 스프링 카페 1단계 - 회원 가입 및 목록 기능
codesquad-members-2022/java-spring-cafe pull request #17
Opened 2022-03-03 07:09 UTC by KTH-96

안녕하세요 항상 리뷰해주시는 리뷰어분들과 호눅스 감사드립니다~~
스프링 카폐 1단계 구현입니다.
아직 Controller테스트 구현을 하지 못했는데 오늘과 내일중으로 Mockito테스트를 공부해서 2단계미션에서는 꼭 추가 하겠습니다. :)

2022-03-03 13:47 UTC, wheejuni requested changes
수고 많으셨습니다 👍 
바로 머지되어도 괜찮은 상황인데, 딱 한가지 마음에 걸리는게 있네요.
이건 꼭 깊이 생각해 주셧음 합니다.

2022-03-03 13:47 UTC, wheejuni commented on src/main/java/com/kakao/cafe/domain/user/UserRepository.java
> +                .get();
`.findAny()` 의 리턴타입이 `java.util.Optional` 이죠?
거기서 `.get()` 을 호출하신 거죠? 혹시 예상되는 위험성이 없을까요? 옵셔널을 받아서 겟 하는 것의...

2022-03-04 07:23 UTC, KTH-96 commented on src/main/java/com/kakao/cafe/domain/user/UserRepository.java
> +                .get();
피드백 감사드립니다 :)
findAny를 쓰면 아이디가 같으면 순서와 관계없이 무작위로 가져오는군요! 감사합니다 아이디 중복시 예외를 추가해야겠습니다!!
옵셔널을 쓰는이유가 반환값이없을때 null을 반환하면 에러가 날확률이 높아서인데 그냥 get을 사용하면 findAny를 사용할필요가 없겠군요 ㅠㅠ orElseGet이나 orElseThrow를 사용하면 될까요??

2022-03-05 05:03 UTC, wheejuni commented on src/main/java/com/kakao/cafe/domain/user/UserRepository.java
> +                .get();
맞습니다! 애써 옵셔널 타입을 받아놓고, 강제로 값을 꺼내서(이것을 [force unwrapping](https://stackoverflow.com/questions/38817494/difference-between-force-unwrapping-optionals-and-implicitly-unwrapped-optionals)이라고 합니다) 옵셔널의 효용을 스스로 포기하는 일이 없어야 겠습니다!

2022-03-05 05:03 UTC, merged