[로니] 스프링 카페 2단계 - 글 쓰기 기능 구현
codesquad-members-2022/java-spring-cafe pull request #33
Opened 2022-03-06 16:02 UTC by CMSSKKK

안녕하세요! 로니입니다😄

2단계 PR 보냅니다!

## 구현

- [x] 글쓰기
- [x] 글 목록 조회하기
- [x] 게시글 상세보기
- [x] 회원정보 수정

항상 꼼꼼하게 리뷰해주시고, 공부할 키워드와 생각할 거리를 남겨주셔서 감사합니다!!

2022-03-08 07:01 UTC, tmdgusya requested changes
전반적으로 자료구조에 `final` 을 사용하신 부분이 좋네요.
코드가 깔끔한 부분들이 많습니다.

아쉬운점은 로그를 찍는 부분이 약간 부실한거 같습니다. 
혹시 코드를 안보고 저 로그만 보고 에러를 찾거나, 어떤 일이 일어났는지 추측이 가능하신가요?
로그는 추적하기 쉬우라고 찍는 것이므로 잘 전달될 수 있는 정보들을 기입해야 합니다.
조금 만 더 신중하게 작성해보시죠 :)

다만 궁금한점과 수정할 사항들이 있어 리뷰 남겨드렸습니다.

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/Article.java
> +    }
전부 같아야만 같은 값인가요? 다름을 구별할 수 있는 유니크한 값은 없나요?

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/MemoryArticleRepository.java
> +    private final List<Article> articles = new ArrayList<>();
자료구조로 List 를 고르신 이유는 무엇일까요?

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/MemoryArticleRepository.java
> +        article.setId(generateId());
자료구조로 List 를 사용하였음에도 불구하고 id 가 필요한 이유는 무엇인가요?

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/MemoryArticleRepository.java
> +        if(checkIndex(index)) {
`checkIndex` 라는 건 정확하게 어떤걸 체크하는지 알기 힘들어보이기도 하네요 ㅎㅎ

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/user/User.java
> +    }
보통 이럴경우 생성자로 해도 되지만 `of` 혹은 `from` 을 많이 사용해요.
한번 이 부분도 찾아보시고 적용해보셔도 좋을거 같아요 ㅎㅎ

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/user/User.java
> -    }
좋습니다 ㅎㅎ

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/service/ArticleService.java
> +            throw new ClientException(HttpStatus.BAD_REQUEST, "게시글을 찾을 수 없습니다.");
BAD REQUEST 가 적절할까요? 더 적절한게 있을거 같은데

Github 에 주소창에 아무 Repository 나 입력하시고 없을경우 어떤 Status Code 가 나오는지 확인해보셔도 좋을거 같아요

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/service/ArticleService.java
> +            throw new ClientException(HttpStatus.BAD_REQUEST, "게시글을 찾을 수 없습니다.");
HTTP METHOD 에 대해서도 공부해 보시는걸 추천드립니다.

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/service/UserService.java
> +    private User findOne(String userId) {
굳이 이 부분을 따로 빼낼이유는 없어보이긴 하는데요 ㅎㅎ
뭐 이건 취향이니 안고치셔도 상관은 없습니다.

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/service/UserService.java
> +            throw new ClientException(HttpStatus.BAD_REQUEST, "아이디가 이미 존재합니다.");
여기도 마찬가지로 BAD_REQUEST 가 적절할까요 ㅎㅎ?
한번 고민해보시죠.

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +public class ArticleController {
`/qna` 가 중복되는거 같은데 Class 상단에 `@RequestMapping` 을 붙이면 중복제거가 가능합니다.
한번 공부해보시고 적용해보세요 ㅎㅎ

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +    public String write(ArticleDto articleDto) {
어떻게 아무것도 안붙였는데 Request Body 를 Dto 로 전환해줄까요 ㅎㅎ? 이 부분에 대해서 공부해보셨나요?

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/UserController.java
> +        logger.info("search {}", id);
로그를 좀만 더 자세하게 찍어보시죠 ㅎㅎ

2022-03-08 07:01 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/dto/ArticleDto.java
> +    @NotBlank
왜 Dto 에서 유효성 검증을 해야 할까요? 이 부분에 대해서 고민하거나 공부해보신적 있으신가요?

2022-03-08 07:01 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/web/dto/UserDtoTest.java
> +        violations.forEach(i -> System.out.println(i.getMessage()));
그다지 좋아보이는 문장은 아닌거 같은데요 ㅎㅎ? 
테스트에서 로그를 찍어야 하나 라는 의문이 있습니다.

2022-03-08 14:37 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/domain/article/Article.java
> +    }
Value Object와 Entity의 차이에 대해서 그룹원이 좋은 글을 공유해준 덕분에 더 고민할 수 있었습니다. 
https://www.culttt.com/2014/04/30/difference-entities-value-objects/

로치가 코멘트남겨주신 의도도 이와 같을까요..?

위 글을 토대로 생각을 정리했을 때, `Article` 객체를 entity로 볼 수 있을 것 같습니다. 

entity의 경우라면 `id`와 같은 identifier만을 체크해서 객체를 판별하면 될까요?

2022-03-08 14:39 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/domain/article/MemoryArticleRepository.java
> +    private final List<Article> articles = new ArrayList<>();
요구사항이라 고민없이 구현한 것 같습니다ㅠㅠ 

요구사항에 의존하기보다 효율적인 자료구조에 대해서 고민하고 구현하겠습니다!

2022-03-08 14:44 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/domain/article/MemoryArticleRepository.java
> +        article.setId(generateId());
article을 구별할 수 있는 고유한 값이 필요하다고 생각합니다!

Map을 활용하도록 해보겠습니다.

2022-03-08 14:46 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/domain/article/MemoryArticleRepository.java
> +        if(checkIndex(index)) {
조금 더 고민해보겠습니다!ㅎㅎ

2022-03-08 14:49 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/service/ArticleService.java
> +            throw new ClientException(HttpStatus.BAD_REQUEST, "게시글을 찾을 수 없습니다.");
예외가 구현의 우선순위가 아니라 생각해서 깊은 고민이 없었던 것 같습니다!

항상 꼼꼼하게 공부하겠습니다. 키워드 감사합니다~

2022-03-08 14:50 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/service/UserService.java
> +    private User findOne(String userId) {
코드가 중복되서 따로 빼봤습니다.. ㅎㅎ

2022-03-08 14:50 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/service/UserService.java
> +            throw new ClientException(HttpStatus.BAD_REQUEST, "아이디가 이미 존재합니다.");
공부하고 수정하겠습니다!

2022-03-08 14:50 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +public class ArticleController {
넵 중복제거하겠습니다 ㅎㅎ

2022-03-08 14:53 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +    public String write(ArticleDto articleDto) {
어노테이션이 없는 경우 `@RequestParam` 혹은 `@ModelAttribute` 으로 처리하는 것으로 알고 있습니다!

 `@ModelAttribute`는 생성자를 통해서 필드를 찾아서 매핑하는 것으로 알고 있습니다!

2022-03-08 14:53 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/web/UserController.java
> +        logger.info("search {}", id);
로그에 대해서도 더 공부하고, 고민하겠습니다! 

로그도 네이밍과 같군요 ....ㅎㅎ

2022-03-08 15:10 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/web/dto/ArticleDto.java
> +    @NotBlank
계층 분리에 대해서 많이 찾아보고 슬랙에 공유해주신 로치의 블로그 글도 봤습니다 ㅎㅎ 

아직 완벽하게 정리하고 제 지식이 되지는 못했지만, 
`Article`을 entity로 보고 다른 책임을 갖지 않도록 하자라는 생각으로 dto에서 검증하도록 했습니다.

2022-03-08 15:12 UTC, CMSSKKK commented on src/test/java/com/kakao/cafe/web/dto/UserDtoTest.java
> +        violations.forEach(i -> System.out.println(i.getMessage()));
Validation 어노테이션을 처음 사용하면서 예제와 비슷하게 테스트를 구현하고, message를 확인해보고자 남긴 코드입니다...

수정하겠습니다!

2022-03-08 15:18 UTC, CMSSKKK commented on src/main/java/com/kakao/cafe/domain/user/User.java
> +    }
저번에 코멘트해주셔서 공부를 했었는데 활용을 못했네요 😂 

활용해보겠습니다 감사합니다!

2022-03-09 03:19 UTC, CMSSKKK commented
안녕하세요 로치😃

코멘트 남겨주신 부분 조금 더 고민하고 수정했습니다.

List 자료구조는 3단계에서 db를 연결하면서 같이 수정해보려고 합니다.
또한 로그에 대해서도 조금 더 공부하고 더 수정해보겠습니다.

코드를 작성하면서 고민하고 해결하는 노력을 하지만, 아직 많이 부족한 것 같습니다.

항상 꼼꼼한 코멘트 덕분에 원리도 조금 더 공부하고, 좋은 코딩 습관을 가질 수 있도록 더 연습하게 된 것 같습니다.

휴일 잘 보내시고 항상 건강 잘 챙기셨으면 좋겠습니다! 감사합니다👍

2022-03-09 06:36 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/dto/ArticleDto.java
> +    @NotBlank
좋네요 ㅎㅎ

2022-03-09 06:36 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/web/ArticleController.java
> +    public String write(ArticleDto articleDto) {
좋네요 :)

2022-03-09 06:37 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/domain/article/Article.java
> +    }
아뇨 제 뜻은 그냥 단순히 entity / value object 가 아니라 유니크한 부분이 없는지 물어본거에요.
unique 한 부분이 있으면 그 부분만 비교해도 되지 않을까 해서요

2022-03-09 06:38 UTC, tmdgusya commented
고생하셨습니다 :)

2022-03-09 06:38 UTC, merged