[Jay] 스프링 카페 1단계 - 회원 가입 및 목록 기능
codesquad-members-2022/java-spring-cafe pull request #37
Opened 2022-03-07 09:12 UTC by jinan159

리뷰어님 안녕하세요. `Jay` 입니다!<br>
**스프링 카페 1단계 - 회원 가입 및 목록 기능** 구현이 완료되어 리뷰 요청드리고자 PR 작성합니다.<br>

# 구현 내용

<details>
<summary>스프링 카페 1단계 - 회원 가입 및 목록 기능</summary>
<h2></h2>

<h3>API 요구사항</h3>

| HTTP Method | URL             | Description |
|-------------|-----------------|-------------|
| POST        | /users          | 회원 가입       |
| GET         | /users          | 회원 목록 조회    |
| GET         | /users/{userId} | 회원 프로필 조회   |

<h3>상세 기능 요구사항</h3>

- [x] 웹페이지 디자인
- [x] 별도의 데이터베이스는 사용하지 않는다.
- [x] 회원 가입 기능 구현
- [x] 회원 목록 조회 기능 구현
- [x] 회원 프로필 조회 기능 구현

<h3>프로그래밍 요구사항<h3>

- [x] 각 기능에 따른 url과 메소드 convention
- [x] 회원가입 기능 구현
- [x] 회원가입 기능 구현
- [x] 회원 프로필 정보보기
- [x] HTML의 중복 제거

</details>

# 신경써서 구현한 부분

1. TDD 로 미션 진행(controller, service 단위테스트, repository 통합테스트)
   TDD 를 해본적이 없어, 장점을 느껴보고자 TDD 로 미션을 진행했습니다.
2. 서비스 중 발생하는 예외를 `CustomException` 으로 별도로 관리하고, `controller` 에서 일괄 처리
   예외의 이름으로 해당 상황을 명확하게 표한하기 위해서 `CustomException` 을 정의하여 사용하였습니다.
3. domain 중심의 패키징
   처음에는 `controller`, `service`, `repository`, `domain` 으로 패키지를 나눴습니다.
   하지만, 특정 업무로직과 관련된 클래스들을 layer 별로 분리하여 따로 관리하는것에 대해 장점을 느끼지 못하여
   같은 업무로직과 관련된 클래스들을 한곳에서 관리하도록 변경하였습니다.
   그래서 현재와 같은 `users` 아래에 `회원` 관련 클래스들이 모두 위치하게 되었습니다.

# 고민사항

1. `단위테스트` vs `통합테스트`
   `controller`, `service` 는 자신이 참조하는 계층을 `Mocking` 하여 테스트를 작성하였습니다.
   그런데 `controller` 테스트 로직에서 `service` 를 `Mocking` 하여 사용하는 상황에서
   `service` 의 로직이 변경되면 `controller` 의 테스트 코드도 수정해야 합니다.
   A를 수정핬는데, A를 참조하는 쪽도 수정해야한다는 것이 바람직한 구조가 아닌것 같기도 하고,
   A가 수정되었으니 `Mocking` 로직도 수정하는것이 당연한것 같기도 해서 생각이 정리가 안되었습니다.
   이런 경우는 `통합 테스트`를 하는것이 맞는지 궁금합니다.
2. 현업에서 `CustomException` 과 자바의 `Exception` 중 어떤것을 선택할지의 기준이 있으신지 궁금합니다.
3. 같은 도메인과 관련된 클래스를 모아서 패키지를 구성했는데, 현업에서 가져가는 패키지 구조는 보통 어떤 모습인지 궁금합니다.
   (혹시 2번 고민과 관련하여 참고할만한 책이나 자료가 있다면, 추천해주시면 정말 감사하겠습니다.)

2022-03-08 08:30 UTC, tmdgusya requested changes
테스트를 작성하시는 습관은 좋네요 ㅎㅎ 💯 
한가지 말씀드리고 싶은 부분은 나아가기 보다는 미션에서 얻어갈 수 있는 부분에 집중하시는게 조금 좋을거 같아요. 현재 미션에서도 얻어갈 수 있는 부분이 많은데 놓치고 계시는거 같기도 해요. 좀 더 고민해보고, 어떤게 좋은 코드인지 더 많이 생각해보세요. 그럼 좋은 개발자가 될 수 있을 겁니다. 💯 

일단 질문에 대한 답은 아래애 드리겠습니다.

1. 써주신 질문이 테스트가 과도하게 구현에 치중했을때 테스트 코드의 수정이 빈번하게 발생하는 문제인데요. 사실 어쩔 수 없는 문제입니다. 이 부분은 지금은 어렵게 이해하실 수 있는데 통합테스트의 경우 여러 Layer 를 관통하는 테스트 입니다. 따라서 Layer 에 수정이 일어날때마다 빈번하게 수정이 일어날 수 밖에 없습니다. 그래서 대부분의 책들에서 단위 테스트의 비중이 높은게 좋다고 말하는 이유 중 하나인데요. 단위 테스트는 보통 다른 계층의 테스트를 덜 받기 때문입니다. 이 부분은 아직은 이해하기 어렵다고 생각이 드네요.

2. 이 부분은 팀의 규율을 따르는데요 보통 ㅎㅎ. 근데 자바의 Exception 으로 표현하기 애매하다면 보통 커스텀 예외를 쓰는거 같아요. 그리고 에러를 좀 관리하기 위해서 커스텀 예외를 많이 적어요.

4. 이 부분은 아직 현업의 수준까지 고민하실 부분은 아닌거 같기도해요 ㅎㅎ. 일단 질문에 답해드리면 저는 회사에서 `육각형 아키텍쳐` 형태로 패키지 구조를 잡고 있어요. 근데 사실 패키지 구조를 이해하고 쓰시려면 레이어간 하는 역할에 대해 이해하셔야 하는데요. 아직 이해하시기 어려워요. 그래서 오히려 기본적인 부분에 좀 더 탄탄해지고 나서 보시는걸 추천드려요. 추천해드리고 싶은 책은 `객체지향의 사실과 오해` 또는 `오브젝트` 를 읽으시는걸 추천드립니다. 레이어간 역할을 모르고 패키지 구조를 잡는건 별로 의미 없는거 같아요. 사실 패키지 구조를 그냥 단순히 스프링에 맞춰서 치는건 별 도움이 되지 않습니다. 자신이 맞다고 생각하는 구조로 잡고 이름도 지어보시고 리뷰를 받으시는게 더 학습이 잘될거에요.

말하다보니 주저리 주저리 떠들게 됬네요.
답변 달아주시고, 수정할 부분 올려주시면 머지해드리겠습니다.

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/controller/UserController.java
> +        }
공통에러로 도출하셨으면 `ExceptionHandler` 에 대해서도 공부해보시면 더 좋은 코드를 작성하실수 있을거 같네요 ㅎㅎ

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/UserService.java
> +    public Optional<Long> join(User user) {
반환이 `Optional<Long>` 인 이유가 있나요 ㅎㅎ?

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/controller/UserController.java
> +                            .collect(Collectors.toUnmodifiableList()));
너무 한줄로 안쓰셔도 됩니다 ㅎㅎ
stream 부터 list 로 만드는 부분은 밖으로 빼내는게 더 깔끔하지 않을까 싶네요 ㅎㅎ..

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/domain/JDBCUserRepository.java
> +public class JDBCUserRepository implements UserRepository {
아직 미션 과정이 아니니 JDBC 쪽은 리뷰하지 않겠습니다.

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/domain/MemoryUserRepository.java
> +        return new User.Builder()
빌더를 사용하는 이유는 뭔가요?

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/domain/MemoryUserRepository.java
> +        LoggerFactory.getLogger(getClass()).info("userRegistry : {}", userRegistry);
LoggerFactory 를 이렇게 쓰시는 건 안좋은 습관입니다 ㅎㅎ
변수로 따로 빼시죠.

로그도 조금 더 자세하게 찍어주시길 바래요. 
아래와 같은 로그가 더 보기 좋은 로그 아닐까요 
`사용자 이름 {}, 기타정보들~~ , 가입 시간 : {}` 대략적으로 이런식이 더 좋아보입니다 ㅎㅎ

로그만으로 에러 추적이 가능할까 생각해보시는걸 추천드려요.

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/domain/MemoryUserRepository.java
> +        LoggerFactory.getLogger(getClass()).info("userRegistry : {}", userRegistry);
지금 정보는 `info` 보다는 `debug` 에 가깝습니다.

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/domain/MemoryUserRepository.java
> +    private void validateRequiredField(User user) {
저는 이게 함수로 validate 되야 하는게 맞는걸까? 라는 생각이 드네요
User 의 필수정보면 User 에 final 로 존재하는거 아닐까요? ㅎㅎ 

책임이 흩어져 있는거 같네요.

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/domain/User.java
> +    public static class Builder {
빌더를 쓰신 이유는 뭘까요 ㅎㅎ?
모두 null 로 들어갈 수 있어보여요.

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/exception/UserDuplicatedException.java
> +public class UserDuplicatedException extends UserRuntimeException {
궁금한 점이 있는데 UserDuplicatedException 이면 외부에서 message 를 받아올 필요가 있을까요?
클래스안에 존재해도 충분하지 않을까 생각해봅니다.

2022-03-08 08:30 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/users/UserServiceTest.java
> +        @DisplayName("User 가 저장되어 있으면, List<User> 를 반환한다.")
테스트 설명이 잘못된거 같아요

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/UserService.java
> +    public Optional<User> findOne(Long id) {
Optional 로 리턴해야 하나요 ㅎㅎ?
이러면 Repository 계층과 역할이 다를게 없어 보이는데요?

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/UserService.java
> +    public Optional<User> findOne(Long id) {
Service 계층을 두셨는데 Service 는 어떤 역할을 하는 계층인가요?

2022-03-08 08:30 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/domain/User.java
> +    }
`getter` 가 다 필요한가요?
단순히 `template` 에 뿌리기 위함이라면 이 클래스가 `template` 에 뿌리는것까지 책임을 가져야 하는지 생각해보시죠
좋은 학습이 될겁니다.

다만 이 부분이 생각하기 어렵다면 지금 처럼 두셔도 상관은 없습니다.
어렵게 느껴질 수도 있다고 생각되서요.

2022-03-08 08:30 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/users/domain/UserRepositoryTest.java
> +                repository.save(user);
`then` 절에 있어야 하는게 맞나요?

2022-03-08 08:30 UTC, tmdgusya commented on src/test/java/com/kakao/cafe/users/domain/UserRepositoryTest.java
> +            // then
`act then act then` 이 반복될 경우 하나의 테스트가 아니지 않을까요?

2022-03-08 09:10 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/UserService.java
> +    public Optional<Long> join(User user) {
Controller 에서 경우에 따라 처리할 수 있도록 하기 위해서 그렇게 했었는데,
다시 생각해보니 Service 에서 Optional 을 처리해서 Controller 에는 정확한 데이터를 반환하는것이 
더 나은 흐름일 것 같다는 생각이 드네요..!
감사합니다!!

2022-03-08 09:10 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/controller/UserController.java
> +        }
해당 부분 공부해보겠습니다. 감사합니다!

2022-03-08 09:10 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/controller/UserController.java
> +                            .collect(Collectors.toUnmodifiableList()));
메소드로 따로 분리해서 의미를 명확하게 전달할 수 있게 개선해보겠습니다!
감사합니다!

2022-03-08 09:17 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/domain/MemoryUserRepository.java
> +        return new User.Builder()
1. `User`를 생성하는데 `Builder` 를 사용하는 이유
    `User` 가 생성될떄 데이터를 주입하고, `getter` 만 제공하여 불변 데이터를 보장하기 위해서 생성자 인자로 값들을 받았습니다.
    그러나 생성자에 인자가 많다보니, 식별하기 어려워서 `Builder`를 통해 생성하는 구조로 만들었습니다.

2. `prepareFirstAddUserAndGet` 메소드에서 `Builder`로 새로 생성하는 이유.
    처음 저장될때, `id`, `createDate`, `modifiedDate`등의 필드를 초기화 해서 넣어주게됩니다.
    이때 회원가입 `view` 에서 넘어온 `User` 에는 위 필드들이 없고, 생성된 이후에는 수정할 수 없기 때문에
    여기서 위 3개의 항목을 추가로 주입하기 위해서 새로 User를 만들었습니다.

2022-03-08 09:20 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/domain/MemoryUserRepository.java
> +        LoggerFactory.getLogger(getClass()).info("userRegistry : {}", userRegistry);
이 부분은 제가 `debug` 용으로 임시로 넣어놨던 로직인데, 미처 빼지 못했던 것 같습니다.
불필요한 로직은 정리하도록 하겠습니다.

로그를 추가할 경우, 말씀하신 형식을 고려하여 로그를 추가하도록 하겠습니다!
감사합니다!

2022-03-08 09:22 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/domain/User.java
> +    public static class Builder {
`User`에 필수로 들어가야하는 정보들을 잘 고려해서 고쳐보겠습니다!
감사합니다😃

2022-03-08 09:23 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/exception/UserDuplicatedException.java
> +public class UserDuplicatedException extends UserRuntimeException {
`CustomException`의 내부에 메세지를 저장하는 방법을 미처 생각을 못했습니다...!!!
감사합니다!!

2022-03-08 09:24 UTC, jinan159 commented on src/test/java/com/kakao/cafe/users/UserServiceTest.java
> +        @DisplayName("User 가 저장되어 있으면, List<User> 를 반환한다.")
다시 보니 List<User> 를 반환한다는 부분이 부적절해 보이네요..ㅠㅠ
작성한 테스트들 쭉 돌아보며 부적절한 부분들 수정하겠습니다.
감사합니다!

2022-03-08 09:26 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/UserService.java
> +    public Optional<User> findOne(Long id) {
말씀하신대로 Service 가 현재 명확한 역할 없이, Repository 의 결과를 그대로 토스하는 듯 한 구조로 되어있습니다..
계층별 역할에 대해 공부를 더 하면서 개선해나가겠습니다.
감사합니다!

2022-03-08 09:30 UTC, jinan159 commented on src/test/java/com/kakao/cafe/users/domain/UserRepositoryTest.java
> +                repository.save(user);
`Given-When-Then` 으로 작성해놓은 코드를 `AAA` 패턴으로 변경하다 빠트린 부분인 것 같습니다!
수정하겠습니다!

2022-03-08 09:31 UTC, jinan159 commented on src/test/java/com/kakao/cafe/users/domain/UserRepositoryTest.java
> +            // then
하나의 테스트가 되도록 수정하겠습니다!

2022-03-08 09:35 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/domain/User.java
> +    }
User Entity 에 저장된 데이터를 외부에서 참조할 수 있도록 모든 멤버변수에 대해 `getter` 를 생성했었습니다.
그러다 보니 `getter`를 남용한 것 같네요..
`getter` 대신에 의미있는 메세지를 통해 접근할 수 있도록 개선해보겠습니다.
감사합니다!!

2022-03-08 09:40 UTC, jinan159 commented on src/main/java/com/kakao/cafe/users/domain/MemoryUserRepository.java
> +    private void validateRequiredField(User user) {
`User` 라는 객체가 단순히 데이터를 저장하는 역할만 해야한다고 생각했는데,
`User` 의 필수 정보를 자기 자신이 알고있는게 맞는 것 같네요!
감사합니다!

2022-03-09 06:40 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/UserService.java
> +    public Optional<Long> join(User user) {
좋네요 :)

2022-03-09 06:42 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/domain/User.java
> +    public static class Builder {
좋습니다.
이참에 Builder 를 사용하실때 유의사항에 대해서도 공부해보세요.

2022-03-09 06:42 UTC, tmdgusya commented on src/main/java/com/kakao/cafe/users/domain/User.java
> +    }
좋네요 :)

2022-03-09 06:43 UTC, tmdgusya commented
고생하셨습니다 ㅎㅎ

2022-03-09 06:43 UTC, merged