[Heyho] 스프링 카페 1단계 - 회원 가입 및 목록 기능
codesquad-members-2022/java-spring-cafe pull request #47
Opened 2022-03-08 12:13 UTC by dongkyu-park

안녕하세요. heyho입니다.
스프링 카페 1단계 기능 구현을 완료하여 PR요청 드립니다.
감사합니다.

2022-03-09 13:39 UTC, wheejuni requested changes
수고 많으셨습니다 💯 
몇가지 질문과 코멘트 남겨 보았어요. 확인 부탁드려요.

2022-03-09 13:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/config/AppConfig.java
> +public class AppConfig {
보통 이렇게 컨피규레이션 클래스를 작성하는 경우에는 계층별로, 혹은 기능별로 클래스를 나눠서 선언하는 편입니다.
`UserRepository` 에 대한 configuration이라면 그 기능에 맞는 클래스 이름을 가지면 좋겠네요!

2022-03-09 13:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/controller/UserController.java
> +    UserService userService;
접근제어자가 누락되어 있군요

2022-03-09 13:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/controller/UserController.java
> +    }
오 생성자 주입 좋습니다 💯

2022-03-09 13:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +        return store.get(store.size() - 1);
이건 어떨까요?

```suggestion
        return user;

2022-03-09 13:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +    }
오 엄청나게 위험한 기능인데 `public` 으로 오픈해도 괜찮나요?

2022-03-09 13:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/UserRepository.java
> +    default void clear() {};
흠 이거 의도를 조금 더 알려주실 수 있을까요?

2022-03-09 17:20 UTC, dongkyu-park commented on src/main/java/com/kakao/cafe/config/AppConfig.java
> +public class AppConfig {
단순히 어플리케이션의 규모가 커져 여러 bean 설정을 해주어야 할 경우 @Component 설정을 한 곳에 모으는 것이 편하겠다는 것에만 초점을 맞춰 생각하고 진행 했었습니다. 하나의 자바 클래스파일에 모든 비즈니스 로직이 들어가는 것과 같은 구조였네요. 감사합니다!!

2022-03-09 17:20 UTC, dongkyu-park commented on src/main/java/com/kakao/cafe/controller/UserController.java
> +    UserService userService;
앗.. 감사합니다

2022-03-09 17:38 UTC, dongkyu-park commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +        return store.get(store.size() - 1);
```java
public User save(User user) {
    store.add(user);
    return user;
}
```

list에 저장되는 Object가 깊은복사로 들어간다고 생각하여 store에 저장되는 user객체와 다른 user를 리턴하는 것이 석연치 않다고 생각하여 해당 방식으로 구현을 했었습니다. 

방금 테스트를 해보니 add로 추가되는 Object는 얕은복사로 들어간다는 것을 이제야 알았습니다. 하하..😂 잘못 된 생각을 바로 잡을 수 있었어요. 감사합니다..!!

2022-03-09 17:49 UTC, dongkyu-park commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +    }
실제로 서비스하는 어플리케이션에서 데이터 저장을 jvm메모리에 올린 채 서비스 될 일은 없다 생각하였고, 메모리 저장소는 개발자가 어플리케이션을 만드는 개발 과정에서 테스트 용도로만 사용될 것이라 생각했기에 깊이 생각하지 않고 초기화 시키는 기능을 넣었습니다. 

사실 테스트 코드를 작성하는 과정에서 추가하게 된 메서드인데 MemoryRepository에서 User가 저장 될 store를 static으로 선언하여 관리하고 있는 상황인데 `public` 오픈을 없애고 다른 방식으로 개선하고자 한다면 어떠한 방법을 사용할 수 있을까요?

2022-03-09 17:53 UTC, dongkyu-park commented on src/main/java/com/kakao/cafe/repository/UserRepository.java
> +    default void clear() {};
앗.. 이건 다른 저장소를 구현체로 만들게 될 경우 데이터를 날려버리는... 기능이 필요하다면 구현하고, 아니면 사용하지 않고의 느낌으로 추가한 부분이였는데 다시 생각해보니 필요성도 없고 무의미한 것 같습니다..😱

2022-03-10 07:15 UTC, dongkyu-park commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +        return store.get(store.size() - 1);
질문 한 가지 드리고 싶습니다. 강의 예제 따라치기 하느라 생각없이 구현한 부분이였는데.. save후 왜 객체를 반환하는가? 에 대한 주제가 모각코방에서 나왔었는데, 명확한 이유를 찾지 못 하겠습니다. 지금 단계에선 필요성이 없어 보이고, jpa와 연관된 것일까?하는 추측만 하고 있는데, 어떤 키워드로 찾아 학습하면 좋을 지 조언을 얻을 수 있을까요?

2022-03-12 08:16 UTC, wheejuni commented on src/main/java/com/kakao/cafe/config/AppConfig.java
> +public class AppConfig {
네 감사합니다. 참고로 애노테이션을 표기하실 때는 백틱 (` `) 으로 감싸시는 것이 다른 사람이 태그되는 참사를 피하는 길입니다 ㅎㅎ

2022-03-12 08:16 UTC, wheejuni commented on src/main/java/com/kakao/cafe/config/AppConfig.java
> +public class AppConfig {
헐... ` 입니다.

2022-03-12 08:17 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +        return store.get(store.size() - 1);
사실 이건 학습이라기보단 공개된 API를 설계하는 관점이나 시각? 생각? 에 관한 문제일 것 같아요.
`내 코드를 쓰는 사람이 내가 아니라면` 이라는 상상에서 출발할 것 같습니다.

2022-03-12 08:18 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +    }
테스트 코드를 작성하는 과정에서 메서드가 추가되면 안됩니다.

2022-03-12 08:18 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/UserRepository.java
> +    default void clear() {};
테스트 코드를 위해 메서드를 추가하면 안되고 스펙은 더더욱 추가하면 안됩니다.
안전한 테스트를 위한 다른 방법을 고민해 보심이 어떠한지요?

2022-03-12 08:19 UTC, wheejuni commented
1단계에서 너무 오래 있는 것 같아 우선 머지합니다~ 코멘트 남겨드린 부분은 고민해주세요. 코멘트가 늦었군요 ㅠ 
@dongkyu-park

2022-03-12 08:19 UTC, merged

2022-03-12 11:53 UTC, dongkyu-park commented
감사합니다😊

2022-03-12 18:38 UTC, dongkyu-park commented on src/main/java/com/kakao/cafe/config/AppConfig.java
> +public class AppConfig {
앗 이해했습니다 감사합니다!