스프링 카페 미션 1단계 - 회원 가입 및 목록 기능
codesquad-members-2022/java-spring-cafe pull request #48
Opened 2022-03-08 13:45 UTC by astraum

안녕하세요, 스프링 카페 미션 1단계 완료하여 리뷰 요청 드립니다. 

스프링이 편리한 도구인 것은 사실이나, 그 이면에서 어떻게 동작하고 있는지 모르는 부분이 많아 더 많은 고민을 하게 되었습니다. 도구와 환경에 대한 이해가 부족하다보니 명확한 의도를 가지고 코드를 구축하기도 어려웠습니다. 

순수 Java에 비해 레퍼런스를 찾기 힘든 경우도 종종 있었는데, 예를 들어 `"redirect:/destination"` 표현에 대한 스프링 공식 문서라던지, mustache 템플릿이 getter 없이도 동작한다던지 하는 것은 검색만으로 찾기가 어려웠습니다. 

동일한 URL에 대해 GetMapping과 PostMapping이 둘 다 존재할 경우, 실제로는 정상적으로 동작함에도 불구하고 `"redirect:/destination"`
코드에서 인텔리제이가 cannot resolve URL 경고를 띄우는 것도 내가 뭔가 잘못한 건지, 인텔리제이의 진단에 오류가 있는 것인지 판단하기가 어려웠습니다.  

그렇게 한참을 헤맨 끝에 2주차에 접어 들어서야 1단계 코드를 제출합니다. 무작정 시간을 들이기보다 조금이라도 더 일찍 제출하고 피드백을 받았다면 보다 효율적인 학습을 할 수 있지 않았을까 하는 아쉬움이 남습니다. 

처음에는 CrudRepository 등 다른 스프링 라이브러리에 존재하는 인터페이스를 흉내내어 만들어 보려다가 일단 미션 상에 명시된 요구사항에 집중하자고 생각하여 꼭 필요한 것 위주로 구현했습니다.

- [x] 회원 가입 기능 구현
  - 회원 가입 양식: /users/form.html
  - 요청 메서드: POST /users
  - 회원 가입 후: 유저 목록으로 리다이렉트 (redirect:/users)
- [x] 회원 조회 기능 구현
  - 요청 메서드: GET /users
  - 회원 목록 뷰 템플릿: /users/list.html
- [x] 회원 프로필 조회 기능 구현
  - 요청 메서드: GET /users/{userId}
  - 회원 프로필 뷰 템플릿: /users/profile.html
- [x] 템플릿을 이용하여 HTML 파일들의 중복 제거
- [x] DB는 사용하지 않는다.
  - 단, 이후 DB를 사용하도록 변경할 수 있어야 한다.

2022-03-09 13:59 UTC, wheejuni requested changes
많은 고민을 하고 충분히 좋은 코드를 짜주신 것 같습니다 💯 💯 
간단한 수정 사항 몇 가지 제안드리니 이것만 반영하시면 좋겠네요.

인텔리제이에서 컴파일 에러가 아닌 경고가 뜨는 경우엔 오탐인 경우도 많습니다.
너무 걱정하지 마시고 애플리케이션 기능 상에(컴파일 타임 및 빌드 타임) 장애가 없다면 무시해도 좋습니다.

2022-03-09 13:59 UTC, wheejuni commented on src/main/java/kr/codesquad/cafe/users/OnMemoryUserRepository.java
> +    private static final AtomicLong nextId = new AtomicLong(1);
동시성에 대한 고민을 하신 것은 좋아요. 👍 
그런데 `static` 으로 선언한 변수에 동시성 안전한 구현체들을 사용하는 것이 어떤 의미를 갖을지도 정확하게 이해하시면 좋겠어요.
쉽게 말해.... `ConcurrentHashMap` 과 `HashMap` 의 차이는 어디에서 오나요? `Long` 과 `AtomicLong` 은요?

2022-03-09 13:59 UTC, wheejuni commented on src/main/java/kr/codesquad/cafe/users/UserController.java
> +            return "redirect:/users";
이 과정을 `service` 에서 하면 안 될까요?

2022-03-09 13:59 UTC, wheejuni commented on src/main/java/kr/codesquad/cafe/users/UserService.java
> +    }
`.orElseThrow()` 로 바꾸면 좋을 것 같군요.

2022-03-09 14:04 UTC, astraum commented on src/main/java/kr/codesquad/cafe/users/UserService.java
> +    }
질문 있습니다! isPresent() 결과로 진입한 if 블록 안에서 orElseThrow()가 예외를 반환하는 경우가 있나요? 아니면 여기서는 문제가 없더라도  orElse~ 유형 메서드를 사용하는 편이 안전한 습관이기 때문에 권장하시는 건가요?

2022-03-09 14:32 UTC, astraum commented on src/main/java/kr/codesquad/cafe/users/UserController.java
> +            return "redirect:/users";
검색해보니 전달받은 값을 도메인 객체로 변환하는 과정을 컨트롤러에서 처리할지, 서비스에서 처리할지에 관해서는 상반되는 의견이 존재했습니다. 저는 UserCreationForm 객체를 다른 계층으로 넘기지 않고 컨트롤러에서 User 객체로 변환하도록 하고, 서비스로는 User 객체를 전달하고 싶어서 이렇게 작성했습니다. 이렇게 했을 경우 문제가 될 수 있는 점이 있다면 짚어주실 수 있을까요?

2022-03-09 14:46 UTC, astraum commented on src/main/java/kr/codesquad/cafe/users/OnMemoryUserRepository.java
> +    private static final AtomicLong nextId = new AtomicLong(1);
어떤 점을 생각해보라고 짚어주신 것인지 잘 이해하지 못했습니다. 조금 더 힌트를 주실 수 있을까요? static 변수에 대해 thread-safe 구현체를 사용하는 것이 어떤 의미를 가지는가... 라는 질문이 너무 막연하고 어렵게 느껴집니다. '쉽게 말해'주신 부분과 어떻게 연결지어 생각해야 할지도 잘 모르겠습니다. 

static으로 선언한 것은 어플리케이션이 하나의 맵과 하나의 auto-increment 값을 공유해야 한다고 생각해서 그런 것이고, 요청을 받을 때마다 새로운 스레드가 생성되어 응답하므로(잘못 알고 있는 것이라면 바로잡아 주시기 바랍니다!) 동시성 문제로부터 보호하기 위하여 thread-safe 객체를 사용했습니다.

2022-03-10 13:07 UTC, astraum commented
지적해주신 부분 수정하면서, 코드가 미션 요구사항에 좀 더 잘 부합하도록 고쳐보았습니다. 확인 부탁드립니다!

2022-03-12 08:21 UTC, wheejuni commented on src/main/java/kr/codesquad/cafe/users/UserController.java
> +            return "redirect:/users";
지금 당장은 문제될 게 없어 보이긴 합니다. 다만 JPA가 섞이기 시작하면 영속성 컨텍스트 관련해서 문제를 겪으실 일이 생길 것 같아요.

2022-03-12 08:22 UTC, wheejuni commented on src/main/java/kr/codesquad/cafe/users/OnMemoryUserRepository.java
> +    private static final AtomicLong nextId = new AtomicLong(1);
제가 코드를 정확히 파악하지 못한 것일 수도 있는데 이 클래스 스프링 빈으로 관리하시지 않았나요?

2022-03-12 11:06 UTC, astraum commented on src/main/java/kr/codesquad/cafe/users/OnMemoryUserRepository.java
> +    private static final AtomicLong nextId = new AtomicLong(1);
예 맞습니다. 첫 PR 시점에서는 SpringAppConfig 클래스에서 빈으로 수동 등록시켰었습니다.

최신 상태에서는 UserRepository 인터페이스를 제거하고 OnMemoryUserRepository 이름을 UserRepository로 바꾸면서 `@Repository`로 컴포넌트 스캔을 통해 등록되도록 바꾸었습니다. 

인터페이스를 제거한 이유는 호눅스로부터 "요구사항에 없는 부분에 대비하기 위해 코드를 늘리지 말아라, 이 미션에서 인터페이스가 꼭 필요했는가"라는 지적이 나왔기 때문입니다.

2022-03-12 11:13 UTC, astraum commented on src/main/java/kr/codesquad/cafe/users/UserController.java
> +            return "redirect:/users";
당장은 잘 와닿지 않지만, 메모해두었다가 JPA와 영속성을 공부할 때 다시 살펴보겠습니다.

2022-03-13 06:35 UTC, wheejuni commented on src/main/java/kr/codesquad/cafe/users/OnMemoryUserRepository.java
> +    private static final AtomicLong nextId = new AtomicLong(1);
네 좋네요. 그렇다면 요청이 들어올때마다 이 객체가 새로 만들어지나요? 애플리케이션에서 이 객체의 생명주기가 어떻게 될까요?
지금 단계에서 고민할 주제가 아닌 거 같긴 한데 이미 이정도의 고민을 하시는 단계인 거 같아 확인해 봅니다.

2022-03-13 06:35 UTC, wheejuni commented
이번 단계에서 충분한 경험은 하신 것 같아 머지합니다~
다음단계에서 지금 해결하지 못한 고민을 이어가주세요

2022-03-13 06:35 UTC, merged

2022-03-13 06:58 UTC, astraum commented on src/main/java/kr/codesquad/cafe/users/OnMemoryUserRepository.java
> +    private static final AtomicLong nextId = new AtomicLong(1);
이 객체는 애플리케이션 실행 시(스프링 컨테이너가 만들어질 때) 하나가 만들어지고, 애플리케이션이 종료될 때(스프링 컨테이너가 닫힐 때)까지 유지됩니다 (필요하다면 `@Bean` 메서드를 통한 수동 설정으로 서로 다른 ID를 가진 여러 개의 객체를 만들 수도 있습니다). 새로운 요청이 들어올 때에는 빈 객체가 새로 만들어지는 것이 아니라 빈에 접근하고 요청에 응답하기 위한 스레드가 만들어집니다.

2022-03-13 07:01 UTC, astraum commented
감사합니다. 짚어주신 부분들을 유념하면서 다음 단계 수행하도록 하겠습니다.