[BC] 스프링 카페 2단계 - 글 쓰기 기능 구현
codesquad-members-2022/java-spring-cafe pull request #61
Opened 2022-03-11 02:22 UTC by honeySleepr

안녕하세요 BC 입니다~~

피가되고 살이되는 리뷰 항상 감사드립니다🙇‍♂️

이번 리뷰도 잘 부탁드립니다!

### 미션 요구사항

- [x] 사용자는 게시글을 작성할 수 있어야 한다.

- [x] 모든 사용자는 게시글 목록을 볼 수 있어야 한다.
    - 작성자와 조회수는 구현하지 못하고 칸만 만들어두었습니다

- [x] 모든 사용자는 게시글 상세 내용을 볼 수 있어야 한다.
    - 제목을 입력하여 상세 내용 조회
    - 작성자와 조회수는

- [ ] (선택) 사용자 정보를 수정할 수 있어야 한다.
    - [x] 회원 목록에서 회원가입한 사용자의 정보를 수정할 수 있어야 한다.
    - [ ] 비밀번호, 이름, 이메일만 수정할 수 있으며, 사용자 아이디는 수정할 수 없다.
        - 비밀번호 수정 기능은 구현하지 못했습니다
    - [x] 비밀번호가 일치하는 경우에만 수정 가능하다.

    * 요구사항의 Put method를 사용하려하였으나 뜻대로 되지 않아 Post를 사용하였습니다

<details>
<summary>실행화면 </summary>
<div markdown="1">

### 글쓰기

![img_1](https://user-images.githubusercontent.com/92678400/157788600-d136b275-404e-4560-bb94-2cf8e0eb93bc.png)

![img_2](https://user-images.githubusercontent.com/92678400/157788602-31c3bbba-30ff-42d0-8c0e-f25ed036be1c.png)

![img_4](https://user-images.githubusercontent.com/92678400/157788665-48a25367-5043-4c3d-ad77-9ca18ba01b10.png)

### 회원 정보 수정

![img_12](https://user-images.githubusercontent.com/92678400/157788790-7de51d38-bbc2-42c8-8ab1-2d3acd405382.png)

![img_13](https://user-images.githubusercontent.com/92678400/157788793-5d8612c3-aa25-49b6-aa2a-81f87052d3e7.png)

![img_14](https://user-images.githubusercontent.com/92678400/157788794-8e58c5b6-24d6-4881-8895-39feee1f167c.png)

</div>
</details>

### 질문있습니다

> getter가 있는 상황에서도 클래스 내부적으로 일치 여부를 확인할 수 있는 메서드를 따로 만들어야 할까요? 

특정 닉네임을 가진 User를 찾을 때 user.getNickname 하지 않고 User 내부에서 직접 물어보는게 좋다는 내용의 리뷰를 보았습니다. 저는 getter가 이미 다른 곳에서 쓰이고
있어서 getter를 없애지 못하는 상황에서 일치 여부 확인 메서드인 matchesNickname(String nickname) 등을 추가로 만들었습니다

이때 getter가 어차피 있는 상황에서는 굳이 matchesNickname() 메서드를 만들지 않고 getter를 활용해서 User 클래스 외부에서 매치 여부를 판단하는게 나은 방법이 아닌지
궁금합니다!

+@:  getter를 없앨 수 있으면 좋겠지만.. 제 머리로는 방법을 찾지 못하였습니다.. 방법이 있을까요..?

2022-03-12 08:39 UTC, wheejuni requested changes
대단히 수고 많으셨습니다. 👍 💯 
변경사항 몇가지 제안 드립니다~

2022-03-12 08:39 UTC, wheejuni commented on .gitignore
> +*.DS_Store
맥북 쓰시는군요

2022-03-12 08:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/domain/User.java
> +    }
게터를 완전히 소거할 방법을 찾지 못했더라도 이렇게 메서드 분리를 시작한 것은 좋은 판단이고 좋은 시도입니다 💯 
일단 분리해내기 시작해야 나중에 게터를 완전히 없앨 방법도 더 빨리 찾을 수 있지 않을까요? 전 그렇게 생각합니다~

2022-03-12 08:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/exception/ErrorMessage.java
> +    BLANK_INPUT("공백만 입력할 수 없습니다.");
👍 HTTP 상태 코드와 매핑도 이뤄지면 더 좋겠는데요?

2022-03-12 08:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/ArticleRepository.java
> +    int save(Article article);
리턴타입 `int` 선택하신 이유가 궁금하군요. 어떤 의미를 갖나요?

2022-03-12 08:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/MemoryArticleRepository.java
> +        int id = articles.size() + 1;
`id`를 `int` 로 고르는 판단.... 좋은 판단일까요? 궁금합니다~

2022-03-12 08:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +    private int sequence = 0;
뭐 그럴일 잘 없겠지만요, 만약 두 개 이상의 스레드가 한번에 여기에 접근하면 어떤 일이 일어날까요?

2022-03-12 08:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +    private int sequence = 0;
바로 위 리스트도 마찬가지요.

2022-03-12 08:39 UTC, wheejuni commented on src/main/java/com/kakao/cafe/service/ArticleService.java
> +            new IllegalArgumentException(ErrorMessage.NO_MATCH_ARTICLE.get()));
`ErrorMessage.get()` 이 아마 문자열 형태의 익셉션 메세지를 전달하나본데요. (맞나요?)
그렇다면 한번에 `ErrorMessage.NO_MATCH_ARTICLE.message` 와 같이 접근하면 안될까요? 굳이 게터? 필요할까요?

2022-03-14 04:27 UTC, honeySleepr reviewed
리뷰 감사드립니다!!
다른건 다 적용하였는데, HTTP 상태코드는 좀 더 공부를 해보고 적용해보겠습니다 ㅎㅎ🙇‍♂️🙇‍♂️

2022-03-14 04:27 UTC, honeySleepr commented on .gitignore
> +*.DS_Store
저게 맥에만 생기는 파일이란걸 최근에 처음 알았습니다ㅎㅎ😅

2022-03-14 04:27 UTC, honeySleepr commented on src/main/java/com/kakao/cafe/repository/ArticleRepository.java
> +    int save(Article article);
`id` 에 대한 `getter`를 대체하고자 하였습니다

그런데 클라이언트 코드 내에서는 리턴값은 쓰지 않고 save(->add) 메서드를 호출만 하고 있고,
`ArticleServiceTest`에서만  id 값을 받을 때 리턴값을 사용합니다. 이렇게 사용해도 괜찮을까요?

2022-03-14 04:27 UTC, honeySleepr commented on src/main/java/com/kakao/cafe/repository/MemoryArticleRepository.java
> +        int id = articles.size() + 1;
여러 스레드에서 접근하는 경우의 동기화를 위해 AtomicInteger를 사용하는게 좋을 것 같습니다

2022-03-14 04:27 UTC, honeySleepr commented on src/main/java/com/kakao/cafe/repository/MemoryUserRepository.java
> +    private int sequence = 0;
`++` 또는 `add`가 제대로 안될 수 있겠네요!
각각 AtomicInteger와 CopyOnWriteArrayList를 적용하겠습니다

2022-03-14 04:27 UTC, honeySleepr commented on src/main/java/com/kakao/cafe/service/ArticleService.java
> +            new IllegalArgumentException(ErrorMessage.NO_MATCH_ARTICLE.get()));
넵 맞습니다 수정하였습니다!

2022-03-14 04:27 UTC, honeySleepr commented on src/main/java/com/kakao/cafe/exception/ErrorMessage.java
> +    BLANK_INPUT("공백만 입력할 수 없습니다.");
넵 더 공부해서 적용해보겠습니다 !

2022-03-15 01:59 UTC, merged